# Generated by Django 3.2.5 on 2023-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbot', '0002_auto_20230316_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='docbot.Symptom'),
        ),
    ]
