# Generated by Django 3.2.5 on 2023-04-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbot', '0003_auto_20230404_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
